apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service
      port: 80 #porta do serviço - o tráfego para o service entra por aqui
      protocol: TCP
      targetPort: 8000 #porta do container que queremos fazer "port-forward"
